### PR TITLE
GB28181: Disable TCP by default. Refine parsing PS stream.

### PR DESCRIPTION
**Pull request by xialixin**
Mainly optimize the PS stream parsing
Solve the problem of screen flickering on Huawei devices
When there are multiple slices in one frame, it was previously treated as multiple frames, which may cause screen flickering
Change jitbuffer to kNoNack, GB does not need to enable nack, IPC does not have feedback mechanism

Corresponding related issues.
https://github.com/ossrs/srs/issues/1852
https://github.com/ossrs/srs/issues/1834.
https://github.com/ossrs/srs/issues/1756
https://github.com/ossrs/srs/issues/2408

---------

`TRANS_BY_GPT3`

### CODE REVIEW

**Comment by yang0705-qiog** [comment]
[2022-04-21 09:34:22.094][Trace][35340][541417u0] gb28181: 34020000001320000001 clients device=34020000001320000001 send invite code=0
[2022-04-21 09:34:31.800][Trace][35340][2e5t50vb] gb28181: client id=34020000001320000001@34020000001320000001,  ssrc=0x8ac006, peer(, 0), rtmp muxer is alive
[2022-04-21 09:34:41.821][Trace][35340][2e5t50vb] gb28181: client id=34020000001320000001@34020000001320000001,  ssrc=0x8ac006, peer(, 0), rtmp muxer is alive
[2022-04-21 09:34:51.116][Trace][35340][2e5t50vb] gb28181: client id=34020000001320000001@34020000001320000001, stream idle timeout, stop!!!
[2022-04-21 09:34:51.116][Trace][35340][2e5t50vb] gb28181: client id=34020000001320000001@34020000001320000001 rtmp muxer is remove
[2022-04-21 09:34:51.116][Trace][35340][2e5t50vb] client finished.
Hello, the above problems still occur when using your directory, huh?

`TRANS_BY_GPT3`

**Comment by ccxyChuzhong** [comment]
> [2022-04-21 09:34:22.094][Trace][35340][541417u0] gb28181: 34020000001320000001 clients device=34020000001320000001 send invite code=0 [2022-04-21 09:34:31.800][Trace][35340][2e5t50vb] gb28181: client id=34020000001320000001@34020000001320000001, ssrc=0x8ac006, peer(, 0), rtmp muxer is alive [2022-04-21 09:34:41.821][Trace][35340][2e5t50vb] gb28181: client id=34020000001320000001@34020000001320000001, ssrc=0x8ac006, peer(, 0), rtmp muxer is alive [2022-04-21 09:34:51.116][Trace][35340][2e5t50vb] gb28181: client id=34020000001320000001@34020000001320000001, stream idle timeout, stop!!! [2022-04-21 09:34:51.116][Trace][35340][2e5t50vb] gb28181: client id=34020000001320000001@34020000001320000001 rtmp muxer is remove [2022-04-21 09:34:51.116][Trace][35340][2e5t50vb] client finished. Hello, using your directory still encounters the above problem.


Hello, it's been two years. Have you solved it? I have also encountered this problem.

`TRANS_BY_GPT3`

**Comment by yang0705-qiog** [comment]
My problem was that the camera configuration was not suitable, but it was fixed after I changed to a different camera.

`TRANS_BY_GPT3`

**Comment by ccxyChuzhong** [comment]
> My problem was that the camera configuration was not suitable, but it was fixed after I changed to a different camera.

> Can you add me on WeChat? I would like to consult with you. I don't know the reason why my post was removed. I have the device now, but the channel is constantly disconnected.

`TRANS_BY_GPT3`

**Comment by yang0705-qiog** [comment]
What camera are you using? I also encountered this problem before, but it was resolved after switching to a Hikvision camera.






------------------ Original Email ------------------

**Comment by ccxyChuzhong** [comment]
I am using Huawei's camera. It is from the D series of Huawei cameras. I feel that the configuration information is a bit different from that of Hikvision, and I cannot find any relevant information either.




------------------ Original Email ------------------
Sender: "ossrs/srs" ***@***.***>;
Sent: July 11, 2022 (Monday) 5:53 PM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject: Re: [ossrs/srs] GB28181: Disable TCP by default. Refine parsing PS stream. (#2668)





What kind of camera are you using? I had the same problem before, but it was resolved after I switched to a Hikvision camera.
 
 
 
 
 
 
------------------ Original Email ------------------

**Pull request merged**
