### PR TITLE
WebRTC: Support WHEP for play. v5.0.182 v6.0.80

### PR DESCRIPTION
**Pull request by winlinvip**
RFC for WHIP: https://datatracker.ietf.org/doc/draft-ietf-wish-whip/

RFC for WHEP: https://datatracker.ietf.org/doc/draft-murillo-whep/

Please note that SRS 5.0 already had WHIP support. I didn't write a document about WHIP, because WHIP is not a RFC right now, but there are clues in [srs-unity](https://github.com/ossrs/srs-unity#usage-publisher). SRS WHIP url for publisher: `http://localhost:1985/rtc/v1/whip/?app=live&stream=livestream`

This PR is for WHEP, the url for player is `http://localhost:1985/rtc/v1/whep/?app=live&stream=livestream`

PS: There is a great PR for OBS to have WHIP support, see https://github.com/obsproject/obs-studio/pull/7926 and #3581 

PS: WHIP for FFmpeg https://github.com/ossrs/ffmpeg-webrtc/pull/1

See #3170

---------

Co-authored-by: Haibo Chen <495810242@qq.com>
Co-authored-by: john <hondaxiao@tencent.com>
Co-authored-by: ChenGH <chengh_math@126.com>

### CODE REVIEW

**Review by chen-guanghua — APPROVED** [review]

**Review by xiaozhihong — APPROVED** [review]

**Comment by johan149** [comment]
Wow great work!

**Comment by winlinvip** [comment]
Seems WHEP is not updated, so we should hold on this PR, and shouldn't merge it util WHEP has some updates.

**Comment by duiniuluantanqin** [comment]
WHEP updated on 2023-03-29,  maybe it can be merged.

> Seems WHEP is not updated, so we should hold on this PR, and shouldn't merge it util WHEP has some updates.

**Comment by zapf2000** [comment]
When ingesting a WHIP stream in Stereo it is downmixed to Mono by WHEP Player.

on WHIP side:
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 cbr=1;maxaveragebitrate=131072;minptime=10;sprop-stereo=1;stereo=1;useinbandfec=1

on WHEP side:
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1

No chance to set the custom parameters stereo=1 or sprop-stereo=1 on client side.

**Pull request merged**
