### PR TITLE
a new PR for HLS AES Encrypt feature

### PR DESCRIPTION
**Pull request by harlanc**
fix the CI test issue

### CODE REVIEW

**Comment by jhaoheng** [comment]
Does srs:v2 will support this feature?

**Comment by harlanc** [comment]
@jhaoheng yes , it will support this feature.

**Comment by winlinvip** [comment]
👍 It seems great

**Comment by harlanc** [comment]
@winlinvip  thanks

**Comment by winlinvip** [comment]
@T-bagwell Please review code whether exists any license problem.

**Comment by harlanc** [comment]
@winlinvip  done

**Comment by winlinvip** [comment]
👍 I will take some time to update wiki and docs. Really good job, buddy!

**Comment by winlinvip** [comment]
Need to support cases that do not rely on SSL.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Refine code: https://github.com/ossrs/srs/commit/1e2cca4712b5de6304d397bdf25e85a72e3975aa

**Comment by harlanc** [comment]
Is it because the licenses of openSSL and SRS are different?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
> Is it because the licenses of openSSL and SRS are different?

> No, it's because during compilation, it allows not to depend on SSL. However, SRS3 may have to depend on SSL.

`TRANS_BY_GPT3`

**Comment by harlanc** [comment]
Oh. But it seems like the code of OpenSSL can be directly used, just need to keep the copyright statement.

`TRANS_BY_GPT3`

**Pull request merged**
