### PR TITLE
Refine AUTHORS.txt to AUTHORS.md, etc. 5.0.8

### PR DESCRIPTION
**Pull request by winlinvip**
https://shimo.im/docs/N2A1MZYlRbTrmJAD

image

image

image

image

image

### CODE REVIEW

**Review by xiaozhihong — APPROVED** [review]

**Review by Bepartofyou — APPROVED** [review]

**Review by xialixin — APPROVED** [review]

**Review by runner365 — APPROVED** [review]

**Review by runner365 — APPROVED** [review]
666666666

**Review by duiniuluantanqin — APPROVED** [review]

**Comment by lipeng19811218** [comment]
approved

**Review by chen-guanghua — APPROVED** [review]
approved

**Review by lipeng19811218 — APPROVED** [review]
approved

**Review by wenjiegit — APPROVED** [review]

**Pull request merged**
