### PR TITLE
RTC: Fix FFmpeg opus audio noisy issue. v5.0.195 v6.0.95

### LINKED ISSUE #3140: WebRTC: Audio is corrupt when using FFmpeg native opus codec. When converting audio AAC to opus using FFmpeg's built-in opus encoding, there is a crackling sound.
**Description**

> If you use the built-in opus in FFmpeg, there will definitely be a loud noise, and this can be reproduced.

> Patch Commit ID: https://github.com/ossrs/srs/commit/8d61c2a064315dfa83d5b29e1068cef00d192561

> SRS Version: `develop` v5.0.36

1. Compile FFmpeg
   * Use FFmpeg's built-in opus: `--enable-decoder=opus --enable-encoder=opus`
   * Use libopus library: `--enable-libopus`

2. SRS Config (Configuration)
```
listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

http_api {
    enabled         on;
    listen          1985;
}

rtc_server {
    enabled on;
    listen 8000; # UDP port
    # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#config-candidate
    #candidate $CANDIDATE;
    candidate 10.254.44.205;
}

vhost __defaultVhost__ {
    rtc {
        enabled     on;
        # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#rtmp-to-rtc
        rtmp_to_rtc on;
        # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#rtc-to-rtmp
        rtc_to_rtmp on;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
}
```

**Replay (Reproduction)**

> Please describe the steps to reproduce the bug. (重现Bug的步骤)

1. RTMP streaming:
`ffmpeg -stream_loop -1  -re -i 264_aac_basline_48k.mp4 -c copy -f flv "rtmp://127.0.0.1/live/livestream"`

2. RTC playback, open the player `https://127.0.0.1/players/rtc_player.html`, and play:
`https://127.0.0.1/players/rtc_player.html`

**Expect (Expected Behavior)**
> RTC playback works normally.

`TRANS_BY_GPT3`

### PR DESCRIPTION
**Pull request by xiaozhihong**
Follow the example in FFmpeg's doc, before calling the API `avcodec_send_frame`, always use `av_frame_alloc` to create a new frame.

---------

Co-authored-by: Haibo Chen <495810242@qq.com>

### CODE REVIEW

**Comment by xiaozhihong** [comment]
Please apply the PR, remove obj dir, and use `--ffmpeg-opus=on` to configure, ensuring the audio play is not noisy.

**Review by winlinvip — APPROVED** [review]

**Comment by winlinvip** [comment]
Test failed when publish by WHIP and play by HTTP-FLV:

```
[2023-10-21 09:48:01.134][INFO][71436][61eia63n] <- RTC RECV #13, udp 1090, pps 108/108, schedule 1090
[2023-10-21 09:48:02.554][INFO][71436][23d23r46] 7B audio sh, codec(10, profile=LC, 2channels, 0kbps, 48000HZ), flv(16bits, 2channels, 44100HZ)
[2023-10-21 09:48:02.574][INFO][71436][23d23r46] time diff to large=2659818625, next out=2716410490, new pkt=2716410510, set to new pkt
```

**Comment by winlinvip** [comment]
如果关闭FFmpeg opus，RTC推流FLV播放，会有崩溃：

```
./configure --ffmpeg-opus=off
```

崩溃信息：

```
=================================================================
==62809==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000060 (pc 0x00010d9f258c bp 0x000111d314b0 sp 0x000111d31440 T1)
==62809==The signal is caused by a READ memory access.
==62809==Hint: address points to the zero page.
    #0 0x10d9f258c in SrsAudioTranscoder::aac_codec_header(unsigned char**, int*) srs_app_rtc_codec.cpp:192

==62809==Register values:
rax = 0x0000000000000060  rbx = 0x0000000111d33020  rcx = 0x0000100000000000  rdx = 0x0000000111d314e0  
rdi = 0x0000608000008f20  rsi = 0x0000000111d314f0  rbp = 0x0000000111d314b0  rsp = 0x0000000111d31440  
 r8 = 0x0000000000000000   r9 = 0x00007fffffffffff  r10 = 0x00007fffffffffff  r11 = 0x00000fffffffffff  
r12 = 0x0000000000000000  r13 = 0x0000000000000000  r14 = 0x0000000000000000  r15 = 0x0000000000000000  
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV srs_app_rtc_codec.cpp:192 in SrsAudioTranscoder::aac_codec_header(unsigned char**, int*)
Thread T1 created by T0 here:
    #0 0x10ed5e52a in wrap_pthread_create+0x5a (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0xcf52a)
    #1 0x10d7f38d9 in SrsThreadPool::execute(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, SrsCplxError* (*)(void*), void*) srs_app_threads.cpp:679
    #2 0x10d9fe949 in run_in_thread_pool() srs_main_server.cpp:475
    #3 0x10d9fdee7 in run_directly_or_daemon() srs_main_server.cpp:414
    #4 0x10d9fb939 in do_main(int, char**, char**) srs_main_server.cpp:242
    #5 0x10d9fe4d3 in main srs_main_server.cpp:253
    #6 0x7ff81a96741e in start+0x76e (dyld:x86_64+0xfffffffffff6e41e)
```

**Comment by winlinvip** [comment]
The default configuration for version 6.0 is `--ffmpeg-opus=on`, while for version 5.0, it's `--ffmpeg-opus=off`. Please handle this when merging.

`TRANS_BY_GPT4`

**Pull request merged**
