### PR TITLE
fix #2797  rtmp推流 rtc播放时 http hooks on_connect on_play 收到的app stream 不一致

### LINKED ISSUE #2797: rtmp推流rtc播放时, http hooks 收到的 app steam 不一致
> 注意：提问前，请先看FAQ(Please read FAQ before file an issue) https://github.com/ossrs/srs/issues/2716

**描述(Description)**

> 当推流地址形如 rtmp://dev-stream.turingvideo.cn:1935/live/436/387236c7d1f4112c4b7d9580cdb047f0时, webrtc播放的时候，on_connect, on_play, on_stop 收到的数据中app及stream不一致。

> on_connect中 app=live  stream=436/387236c7d1f4112c4b7d9580cdb047f0

> on_play及on_stop中  app=live/436  stream=387236c7d1f4112c4b7d9580cdb047f0

1. SRS版本(Version):  4.0-Release

1. SRS的日志如下(Log):
image

1. SRS的配置如下(Config):
```
# main config for srs.
# @see full.conf for detail config.

listen              1935;
max_connections     10000;
srs_log_tank        console;
daemon              off;
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}
stats {
    network         0;
    disk            sda sdb xvda xvdb;
}
rtc_server {
    enabled         on;
    # Listen at udp://8000
    listen          8000;
    #
    # The $CANDIDATE means fetch from env, if not configed, use * as default.
    #
    # The * means retrieving server IP automatically, from all network interfaces,
    # @see https://github.com/ossrs/srs/issues/307#issuecomment-599028124
    candidate       $CANDIDATE;
}
vhost __defaultVhost__ {
    tcp_nodelay     on
    min_latency     on;

    hls {
        enabled         off;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
    rtc {
        enabled     on;
        bframe      discard;
        rtmp_to_rtc on;
        rtc_to_rtmp off;
    }
    play {
        gop_cache       off;
        queue_length    10;
        mw_latency      0;
    }

    publish {
        mr off;
        # mr_latency 100;
        normal_timeout 600000;
    }

    http_hooks{
        enabled       on;
        # 172.18.0.3 => srs_hook container ip
        on_connect    http://172.18.0.3:8085/api/srs/hooks/connect;
        on_close      http://172.18.0.3:8085/api/srs/hooks/close;
        # on_publish    http://172.18.0.3:8085/api/srs/hooks/publish;
        # on_unpublish  http://172.18.0.3:8085/api/srs/hooks/unpublish;
        on_play       http://172.18.0.3:8085/api/srs/hooks/play;
        on_stop       http://172.18.0.3:8085/api/srs/hooks/stop;
        # on_dvr        http://172.18.0.3:8085/api/srs/hooks/dvr;
        # on_hls        http://172.18.0.3:8085/api/srs/hooks/hls;
        # on_hls_notify http://172.18.0.3:8085/api/srs/hooks/hls_notify;
    }
}

```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. ffmpeg 推流到形如 rtmp://dev-stream.turingvideo.cn:1935/live/436/387236c7d1f4112c4b7d9580cdb047f0 的地址。
2. webrtc播放流，播放地址：webrtc://dev-stream.turingvideo.cn/live/436/387236c7d1f4112c4b7d9580cdb047f0。
3. 查看srs日志即复现。

**期望行为(Expect)**

> 期望rtmp推流rtc播放时候，on_connect on_play on_stop 中，app stream 等信息一致。

### PR DESCRIPTION
**Pull request by xupeng1206**
我不是个c++的码农，根据自己理解尝试改了一下，不知道改的对不对，麻烦老师傅们看一下，不对的话，close掉就好。

跟了一下代码，发现webrtc play的时候 以webrtc://localhost/live/123/uuid 从右边开始找第一个斜线，将第一个斜线右边做stream,前面部分做为tcUrl，导致最后匹配出来，app=live/123 stream=uuid.

rtmp推流端，实测是app=live stream=123/uuid, 看起来是从左边开始匹配。这部分代码没能找到位置。

### CODE REVIEW

**Comment by winlinvip** [comment]
Thank you for the PR, 👍 
The colleague in charge of API maintenance has been busy these past two weeks. They should have some free time to take a detailed look after New Year's Day. Please wait a little longer, thank you.

`TRANS_BY_GPT3`

**Comment by dzxiang** [comment]
I don't know if it's the same issue, but here is the streaming address on my side:
rtmp://183.56.xxx.yy:1935/live/3abacde4f0da4f42a2ba384321aa44fd
The generated streaming address has changed to:
http://183.56.xxx.yy:7080/liv/3abacde4f0da4f42a2ba384321aa44fd.flv

The "live" part has changed to "liv". Strangely, it started working again after switching to a different server.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
> 

It should not be the same issue. Please confirm the reproduction path and raise a new issue.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
> rtmp push end, the actual test is app=live stream=123/uuid, it seems to match from the left side. Couldn't find the location of this part of the code.

How did you test it? I tested it as app=live/123, stream=uuid here.

In addition, if you must have support for multi-level streams, I suggest you customize and modify it yourself. The official version is unlikely to make such changes. This PR has been closed.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
We do not support multi-level streams because we have adopted a simplified URL rule, similar to directories and files. It is like the stream name is in the file name, and the app has multiple levels as directories.

This way is simpler and sufficient for general business use, and the analogy is also more intuitive.

Anyway, thank you very much @xupeng1206 for submitting the PR. Thank you for your time and enthusiasm. Please feel free to look at other issues and continue submitting PRs.

Also, thank you @duiniuluantanqin for taking the time to review the PR and discuss it.

Once again, thank you.

`TRANS_BY_GPT3`

**Pull request closed without merging**
