### PR TITLE
GB: Support enabling media forwarding through API instead of SIP.

### LINKED ISSUE #3369: GB28181 push stream failed, SRS 5008 error
National standard flow push failed, log prompt:
```err: code=5008(RtcStun)(RTC do STUN or ICE failed) ```

The INVITE request message is as follows:
```INVITE sip:51190200041320000008@192.168.0.101:5860;transport=udp SIP/2.0
Call-ID: e7634e25054f61ebbe6adf528baf7c16@192.168.0.104
CSeq: 1527 INVITE
From: <sip:51190200042000000001@5119020004:5060>;tag=1673234007732
To: <sip:51190200041320000008@192.168.0.101:5860>
Via: SIP/2.0/UDP 192.168.0.104:5060;branch=z9hG4bK1673234007732
Max-Forwards: 70
User-Agent: ldscloud V1.0.1
Content-Encoding: GB2312
Subject: 51190200041320000008:0902000001,192.168.0.104:0
Content-Type: Application/SDP
Content-Length: 206

v=0
o=51190200041320000008 0 0 IN 192.168.0.104
s=Play
c=IN IP4 192.168.0.106
t=0 0
m=video 8000 RTP/AVP 96 98 97
a=recvonly
a=rtpmap:96 PS/90000
a=rtpmap:98 H264/90000
a=rtpmap:97 MPEG4/90000
y=0902000001```
```
1. SRS Version:  5.0.128
```
```
2. SRS Log:

```
[2023-01-09 03:09:01.284][INFO][1][963c6429] Process: cpu=1.00%,49MB, threads=2
[2023-01-09 03:09:02.205][WARN][1][m173ps86][11] handle udp pkt, count=1/1, err: code=5008(RtcStun)(RTC do STUN or ICE failed) : size=1172, data=[80 60 00 01 00 20 ba bd] : no session, peer_id=192.168.0.101:12002, fast=-2148779970514605888
thread [1][m173ps86]: cycle() [./src/app/srs_app_listener.cpp:743][errno=11]
thread [1][m173ps86]: on_udp_packet() [./src/app/srs_app_rtc_server.cpp:430][errno=11]
[2023-01-09 03:09:02.205][INFO][1][m173ps86] <- RTC RECV #15, udp 1, pps 0/0, schedule 1
[2023-01-09 03:09:03.553][INFO][1][84yn0d8f] Hybrid cpu=2.99%,50MB, cid=72,1, timer=58,0,0, clock=0,14,31,0,0,0,0,0,0
[2023-01-09 03:09:06.296][INFO][1][963c6429] Process: cpu=3.00%,51MB, threads=2
[2023-01-09 03:09:08.554][INFO][1][84yn0d8f] Hybrid cpu=4.00%,52MB, cid=72,1, timer=58,0,0, clock=0,14,31,0,0,0,0,0,0
[2023-01-09 03:09:11.305][INFO][1][963c6429] Process: cpu=3.99%,53MB, threads=2
[2023-01-09 03:09:12.210][WARN][1][m173ps86][11] handle udp pkt, count=5152/5152, err: code=5008(RtcStun)(RTC do STUN or ICE failed) : size=1172, data=[80 60 14 20 00 2e 80 fa] : no session, peer_id=192.168.0.101:12002, fast=-2148779970514605888
thread [1][m173ps86]: cycle() [./src/app/srs_app_listener.cpp:743][errno=11]
thread [1][m173ps86]: on_udp_packet() [./src/app/srs_app_rtc_server.cpp:430][errno=11]
[2023-01-09 03:09:12.210][INFO][1][m173ps86] <- RTC RECV #15, udp 5151, pps 4/514, schedule 5151
[2023-01-09 03:09:13.554][INFO][1][84yn0d8f] Hybrid cpu=3.00%,54MB, cid=517,1, timer=61,0,0, clock=0,28,19,0,0,0,0,0,0
[2023-01-09 03:09:16.313][INFO][1][963c6429] Process: cpu=4.00%,55MB, threads=2
[2023-01-09 03:09:18.554][INFO][1][84yn0d8f] Hybrid cpu=4.00%,56MB, cid=517,1, timer=61,0,0, clock=0,28,19,0,0,0,0,0,0
[2023-01-09 03:09:21.322][INFO][1][963c6429] Process: cpu=4.00%,57MB, threads=2
[2023-01-09 03:09:22.259][WARN][1][m173ps86][11] handle udp pkt, count=10601/10601, err: code=5008(RtcStun)(RTC do STUN or ICE failed) : size=1172, data=[80 60 29 69 00 3c 4b e2] : no session, peer_id=192.168.0.101:12002, fast=-2148779970514605888
thread [1][m173ps86]: cycle() [./src/app/srs_app_listener.cpp:743][errno=11]
thread [1][m173ps86]: on_udp_packet() [./src/app/srs_app_rtc_server.cpp:430][errno=11]
```

3. SRS Config:

```
# docker config for srs.
# @see full.conf for detail config.

listen              1935;
max_connections     1000;
# For docker, please use docker logs to manage the logs of SRS.
# See https://docs.docker.com/config/containers/logging/
srs_log_tank        console;
daemon              off;

http_api {
    enabled         on;
    listen          1985;
    https {
        enabled on;
        listen 1990;
        key ./conf/ssl/ldscloud.cn.key;
        cert ./conf/ssl/ldscloud.cn_bundle.crt;
   }
}
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
    https {
        enabled on;
        listen  8088;
        key ./conf/ssl/ldscloud.cn.key;
        cert ./conf/ssl/ldscloud.cn_bundle.crt;

    }
}
rtc_server {
    enabled on;
    listen 8000;
    # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#config-candidate
    candidate 192.168.1.11;
    tcp {
        # Whether enable WebRTC over TCP.
        # Overwrite by env SRS_RTC_SERVER_TCP_ENABLED
        # Default: off
        enabled on;
        # The TCP listen port for WebRTC. Highly recommend is some normally used ports, such as TCP/80, TCP/443,
        # TCP/8000, TCP/8080 etc. However SRS default to TCP/8000 corresponding to UDP/8000.
        # Overwrite by env SRS_RTC_SERVER_TCP_LISTEN
        # Default: 8000
        listen 8000;
    }
    # The protocol for candidate to use, it can be:
    #       udp         Generate UDP candidates. Note that UDP server is always enabled for WebRTC.
    #       tcp         Generate TCP candidates. Fail if rtc_server.tcp(WebRTC over TCP) is disabled.
    #       all         Generate UDP+TCP candidates. Ignore if rtc_server.tcp(WebRTC over TCP) is disabled.
    # Note that if both are connected, we will use the first connected(DTLS done) one.
    # Overwrite by env SRS_RTC_SERVER_PROTOCOL
    # Default: udp
    protocol all;
}
vhost __defaultVhost__ {
    hls {
        enabled         on;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
    rtc {
        enabled     on;
        # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#rtmp-to-rtc
        rtmp_to_rtc on;
        # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#rtc-to-rtmp
        rtc_to_rtmp on;
    }

   http_hooks {
        enabled         off;
        on_publish      https://10.0.0.1:9080/api/v1/streams;
        on_unpublish    https://10.0.0.1:9080/api/v1/streams;
        on_play         https://10.0.0.1:9080/api/v1/sessions;
        on_stop         https://10.0.0.1:9080/api/v1/sessions;
        on_dvr          https://10.0.0.1:9080/api/v1/dvrs;
        on_hls          https://10.0.0.1:9080/api/v1/hls;
        on_hls_notify   https://10.0.0.1:9080/api/v1/hls/[app]/[stream]/[ts_url][param];
    }
}
```

`TRANS_BY_GPT3`

### LINKED ISSUE #3550: GB: How to make SRS5 only receive PS streams without using the internal SIP?
> Note: Please read FAQ before file an issue, see #2716

## Description

Please description your issue here

1. SRS Version: srs5

2. SRS Log:

image

3. SRS Config:

```
stream_caster {
    enabled on;
    caster gb28181;
    listen 10000;
    sip {
        enabled off;
    }
}
```

## Replay

Please describe how to replay the bug?

Step 1: srs5 only opens the national standard monitoring port. If the built-in SIP is disabled, the project cannot be started. If the built-in SIP is enabled, the project can be started. However, if an external PS stream is sent to srs, it will report "no session" and the stream will be discarded.

## Expect
I only receive PS streams and do not use the internal SIP. I use an external independent SIP service.

`TRANS_BY_GPT3`

### LINKED ISSUE #3733: Error occurred when running gb28181 with internal SIP closed.
> Note: Please read FAQ before file an issue, see #2716

## Description

When using the internal SIP of SRS and only forwarding PS streams, SRS will start with an error.

1. SRS Version:6
2

3. SRS Config:

```
listen 1935;
max_connections 1000;
daemon off;
srs_log_tank console;

stream_caster {
    enabled on;
    caster gb28181;
    output rtmp://10.10.1.111:1935/live/[stream];
    listen 9000;
    tcp_enable  on;
    sip {
        enabled off;
        listen 5060;
                serial  34020000002000000001;
                auto_play       on;
        # @see https://ossrs.net/lts/zh-cn/docs/v5/doc/gb28181#config-candidate
        candidate 10.10.1.111;
    }
}

http_server {
    enabled on;
    listen 8080;
    dir ./objs/nginx/html;
}

http_api {
    enabled on;
    listen 1985;
        crossdomain     on;
        raw_api {
        # whether enable the HTTP RAW API.
        # default: off
        enabled             off;
        # whether enable rpc reload.
        # default: off
        allow_reload        off;
        # whether enable rpc query.
        # default: off
        allow_query         off;
        # whether enable rpc update.
        # default: off
        allow_update        off;
    }
}
stats {
    network 0;
}
rtc_server {
    enabled on;
    listen 8000; # UDP port
    # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#config-candidate
    candidate 10.10.1.111;
}

vhost __defaultVhost__ {
    tcp_nodelay     on;
    min_latency     on;
    
    play {
        gop_cache       off;
        queue_length    10;
        mw_latency      100;
    }

    publish {
        mr off;
    }
    rtc {
        enabled on;
        # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#rtmp-to-rtc
        rtmp_to_rtc on;
        # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#rtc-to-rtmp
        rtc_to_rtmp on;
    }
    http_remux {
        enabled on;
        mount [vhost]/[app]/[stream].flv;
    }
    hls {
        enabled on;
    }
        dvr {
        enabled      on;
        dvr_path     /root/srs-video/[app]/[stream]/[stream].[timestamp].mp4;
        dvr_plan     session;
    }
}
```

## Replay

When using the internal SIP of SRS and only forwarding PS streams, SRS will encounter an error during startup.

## Expect

How to integrate a custom SIP system with SRS to achieve PTZ control for GB28181?

`TRANS_BY_GPT3`

### PR DESCRIPTION
**Pull request by duiniuluantanqin**
Support external signaling service, SRS only acts as a media server. Simply push RTP directly.

for https://github.com/ossrs/srs/issues/3369

---------

`TRANS_BY_GPT3`

### CODE REVIEW

**Comment by winlinvip** [comment]
External signaling is certainly needed.

I took a quick look and have a question: Is it generally allocated in SDP to determine if the incoming SSRC is valid?

It seems that there is currently no API available, so it is assumed that all are accepted by default. The URL used is the SSRC instead of the device ID. It would be better to provide an HTTP API to set the device ID corresponding to the SSRC for better consistency.

Of course, an HTTP API would be more complex. We can consider if there are any better solutions available.

`TRANS_BY_GPT3`

**Comment by zh19900725** [comment]
> 支持外置信令服务，srs仅作为媒体服务器。直接推送rtp即可。 以`ssrc`作为stream id，比如`ssrc`值为`1234567890`，那么url为`rtmp://127.0.0.1/live/1234567890`
> 
> for #3369

不行啊，srs 5.0release分支 我直接推rtp流，报了这个错误，切到srs4可以
[2023-06-13 16:32:19.692][WARN][28748][6159p03l][11] PS: Ignore packet length=1000 for no session
[2023-06-13 16:32:19.692][WARN][28748][6159p03l][11] PS: Ignore packet length=120 for no session
[2023-06-13 16:32:19.693][WARN][28748][6159p03l][11] PS: Ignore packet length=1412 for no session
[2023-06-13 16:32:19.693][WARN][28748][6159p03l][11] PS: Ignore packet length=1412 for no session
[2023-06-13 16:32:19.693][WARN][28748][6159p03l][11] PS: Ignore packet length=1412 for no session
[2023-06-13 16:32:19.693][WARN][28748][6159p03l][11] PS: Ignore packet length=1412 for no session
[2023-06-13 16:32:19.693][WARN][28748][6159p03l][11] PS: Ignore packet length=1412 for no session
[2023-06-13 16:32:19.695][WARN][28748][6159p03l][11] PS: Ignore packet length=1076 for no session
[2023-06-13 16:32:19.695][WARN][28748][6159p03l][11] PS: Ignore packet length=96 for no session
[2023-06-13 16:32:19.704][WARN][28748][6159p03l][11] PS: Ignore packet length=100 for no session


配置文件：
stream_caster {
    enabled on;
    caster gb28181;
    output rtmp://127.0.0.1/live/[stream];
    listen 9000;
    auto_create_channel on;
    sip {
        enabled on; 
        listen 5060;
        # @see https://ossrs.net/lts/zh-cn/docs/v5/doc/gb28181#config-candidate
        candidate $CANDIDATE;
    }
}

**Comment by duiniuluantanqin** [comment]
Add a new API, `gb/v1/publish`.

First, you can use Postman or a similar tool to send an HTTP POST request, as shown below.
```
POST /gb/v1/publish/
{
    "clientip": "192.168.1.100",
    "stream": "testname",
    "ssrc": "1234567890"
}
```
- `ssrc` is randomly generated, typically a 10-digit number, and you should ensure its global uniqueness.
- `stream` is the name of the stream, which you can use to pull the stream.


Then, you should recieve the response like:
```
{"port":9000, "is_tcp": true}
```
This indicates that the srs listening port is 9000. 
> currently srs only supports TCP transmission.


Now, you can use srs_bench to push RTP over TCP. The usage is as follows:
```
srs_bench -sfu gb28181 -mr tcp://127.0.0.1:9000 -ssrc 1234567890 -sa avatar.aac -sv avatar.h264 -fps 25
```
Finally, you can test the stream with:
```
rtmp://127.0.0.0/live/testname
```

`TRANS_BY_GPT4`

**Comment by duiniuluantanqin** [comment]
add gb_test func `TestGbPublishWithApi`
you can just test it with the commond
```
srs_gb28181_test --test.run TestGbPublishWithApi
```

**Comment by duiniuluantanqin** [comment]
https://github.com/ossrs/srs-sip
An external SIP signaling server that accompanies the SRS package.

`TRANS_BY_GPT4`

**Comment by duiniuluantanqin** [comment]
Please refer to the following GitHub pull request: https://github.com/ossrs/srs/pull/4101

`TRANS_BY_GPT4`

**Pull request closed without merging**
