### PR TITLE
Support g711a and g711mu in webrtc without audio transcoding.

### PR DESCRIPTION
**Pull request by qichaoshen82**
In Video surveillance, device's audio codec may be g711a or g711mu, and these two audio codecs are supported in the chrome webrtc audio codec list.

Support g711a and g711mu without audio transcoding.

### CODE REVIEW

**Comment by duiniuluantanqin** [comment]
需要把`kG711aAudioChannel`和`kG711muAudioChannel`两个变量设置为0，否则没有声音。
Chrome 版本 90.0.4430.93
Firefox 版本 88.0.1

**Comment by qichaoshen82** [comment]
https://tools.ietf.org/pdf/draft-roach-mmusic-unified-plan-00.pdf

example sdp section:
///////////////////////////////
m=audio 55400 RTP/SAVPF 0 96
 a=msid:ma ta
 a=extmap:1 urn:ietf:params:rtp-hdrext:stream-correlator 24860
 a=mid:1
 a=rtpmap:0 PCMU/8000
 a=rtpmap:96 opus/48000
 a=ptime:20
 a=sendrecv
 a=rtcp-mux
 a=ssrc:35987
 a=candidate:0 1 UDP 2113667327 203.0.113.2 55400 typ host
/////////////////////////////

**Review by duiniuluantanqin — APPROVED** [review]

**Review by duiniuluantanqin — APPROVED** [review]

**Review by duiniuluantanqin — APPROVED** [review]

**Comment by xianchuhan** [comment]
Looking at this g711 process, does feature/g711 already support audio g711a/g711u encoding?

`TRANS_BY_GPT3`

**Comment by qichaoshen82** [comment]
@xianchuhan  Already supported

`TRANS_BY_GPT3`

**Comment by xianchuhan** [comment]
@qichaoshen82 There is a problem with the webrtc streaming side, or is it only supporting opus?
https://github.com/ossrs/srs-g711/commit/f2e0cb83b90e2280d521d8b2a535551478472128

`TRANS_BY_GPT3`

**Comment by qichaoshen82** [comment]
@xianchuhan I tested it by pushing it up through the rtmp protocol. The rtmp protocol can support g711. I haven't tried pushing it directly with webrtc, but it should also be possible. Just need to adjust the frontend code implementation a bit.

`TRANS_BY_GPT3`

**Comment by xianchuhan** [comment]
@qichaoshen82 I mean, the audio codec for the srs webrtc server-side streaming is hardcoded to opus by default. I made some changes to the code today, and now it works.
Also, there is a problem with the SDP answer on the srs webrtc play side. This "a=rtpmap:63 red/48000/2" should be for opus audio format, but it is not declared here. Including this seems unnecessary, as shown in the image below: 
image

`TRANS_BY_GPT3`

**Comment by qichaoshen82** [comment]
Okay. Let me take a look at the code. If the audio is in the g711 series when playing, the option for opus should be removed.

`TRANS_BY_GPT3`

**Pull request merged**
