### PR TITLE
Security: Enable CIDR for allow/deny play/publish

### LINKED ISSUE #1190: SRS的Security规则能否添加网段？
SRS的Security规则能否添加网段？比如 allow play 192.168.0.0/16;以增加添加规则的方便性。

### PR DESCRIPTION
**Pull request by macabu**
Previously you could only specify static IPs to the security config, this PR enables specifying ranges of IPs in a network.  
Tests added and passing.  

Fixes #1190

Thanks

### CODE REVIEW

**Comment by matclayton** [comment]
This would be very useful for us, any chance this could be merged?

**Comment by winlinvip** [comment]
Thanks for your PR. 👍 

I think it's very good to support CIDR for security, and the utest is in this PR which is very nice.

However, I need more time to think about it.

Please keep this PR here and others could pick it to their repository and test it.

**Review by duiniuluantanqin — APPROVED** [review]

**Comment by winlinvip** [comment]
Really appreciate this patch, thanks a lot.

I notice there is some codes copied from blog, but the LICENSE is not clear, so please rewrite these functions. Please check the code from Go or Nginx, both LICENSE are ok. 😄 
 
```
// Convert an IPv4 from string to uint32_t. Extracted from https://www.stev.org/post/ccheckanipaddressisinaipmask
extern uint32_t srs_ipv4_to_num(std::string ip);

// Whether the IPv4 is in an IP mask. Extracted from https://www.stev.org/post/ccheckanipaddressisinaipmask
extern bool srs_ipv4_within_mask(std::string ip, std::string network, std::string mask);
```

**Comment by winlinvip** [comment]
@macabu @matclayton I have reviewed this PR and some codes are delivered under unspecified license, copied from the blog website, so @duiniuluantanqin fixed this and file a new PR #2914 which is based on this one (the commits are kept and new commits are added).

Appreciated for all you 👍

**Comment by winlinvip** [comment]
Moved to #2914

**Pull request closed without merging**
