### PR TITLE
Support HEVC/H.265 in SRT/RTMP/HLS.

### PR DESCRIPTION
**Pull request by runner365**
modify assert

### CODE REVIEW

**Comment by winlinvip** [comment]
👍 Please ask Mr. Shi to provide additional information on Usage, which includes how to stream, how to configure SRS, and how to watch.

`TRANS_BY_GPT3`

**Comment by runner365** [comment]
> 👍 Please Mr. Shi, provide some additional information on Usage, such as how to push the stream, how to configure SRS, and how to watch it.

Hevc has written two wikis, can you help take a look when you're free?
https://github.com/ossrs/srs/wiki/v1_CN_hevc#
https://github.com/ossrs/srs/wiki/v4_CN_SRTCodec

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Previously, there was PR to support h.265 in RTMP, please refer to #1721.

I will first merge h.265 into the [feature/h265](https://github.com/ossrs/srs/tree/feature/h265) branch, and in the future, I will consider merging it into develop. Students who need it can easily merge it into their own SRS branch.

`TRANS_BY_GPT3`

**Comment by wusopp** [comment]
> > +1 Please ask Mr. Shi to provide additional information on Usage, such as how to push the stream, how to configure SRS, and how to watch it.
> 
> I have written two wikis about HEVC. If you have time, please help take a look.
> https://github.com/ossrs/srs/wiki/v1_CN_hevc#
> https://github.com/ossrs/srs/wiki/v4_CN_SRTCodec

> May I ask if HTTP-FLV playback is supported? If not, are there any plans for future updates? Thank you.

`TRANS_BY_GPT3`

**Comment by Amon8859** [comment]
The information about the H265 stream in the '/api/v1/streams' interface is incorrect.

`TRANS_BY_GPT3`

**Pull request merged**
