### PR TITLE
RTC: Add G.711-A and G.711-U audio codec.

### PR DESCRIPTION
**Pull request by qichaoshen82**
In Video surveillance, device's audio codec may be g711a or g711u, and these two audio codecs are supported in the chrome webrtc audio codec list.So we can support these two audio codecs in SRS without any audio transcoding.
First, add the g711a and g711u flv demuxer, I will add other implement for webrtc later.

### CODE REVIEW

**Comment by winlinvip** [comment]
Additional background information: 

Shen Qichao: For video surveillance, the audio and video streams are converted from SRS to WebRTC. It was found that many video surveillance audios are in formats such as G711a and G711mu, which are also supported in the FLV specification. The WebRTC payload of Chrome and Safari also supports these formats, so there is no need for audio transcoding to complete the process. I implemented these functionalities using tag 99, and the playback of G711 audio in the browser works fine.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
Is the author continuing to improve?

`TRANS_BY_GPT3`

**Comment by qichaoshen82** [comment]
@duiniuluantanqin 
It has been perfected based on the new develop code. However, in order to reduce code conflicts, I hope to first merge some basic functionalities.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
> @duiniuluantanqin
> It has been completed based on the new develop code. However, in order to reduce code conflicts, I hope to first merge some basic functionalities.

> Boss Yang probably won't merge into the dev branch, but will create a new g711 branch. So you can submit all at once. Submit and I will help you verify.

`TRANS_BY_GPT3`

**Comment by qichaoshen82** [comment]
give another PR that implement all of this function

**Comment by qichaoshen82** [comment]
@duiniuluantanqin 
https://github.com/ossrs/srs/pull/2401

**Pull request closed without merging**
