### PR TITLE
Transcode: Support video codec such as h264_qsv and libx265. v6.0.145

### PR DESCRIPTION
**Pull request by jb-alvarado**
Currently only libx264 ffmpeg encoder is supported. This pull request add also h264_qsv. But maybe a more generic solution with oder encoders would be useful to.

### CODE REVIEW

**Comment by winlinvip** [comment]
I think it's also reasonable to support libx265?

**Comment by jb-alvarado** [comment]
Sure! And there is also VP8/9 and AV1. But I ask my self is it really necessary to limit the codec? What if someone only wants to record the stream to disk with a different codec, or stream something exotic over UDP?

The other question to is, is the check of `vprofile.empty()` and `vpreset.empty()` needed? When a codec supports this, and the setting is not present then it uses a default.

But I'm following your lead here.

**Comment by winlinvip** [comment]
The transcoding feature is a subset of FFmpeg, limited to protocols supported by RTMP, so there's no need to support VP8/VP9/AV1 at the moment.

Supporting all codecs and parameters that FFmpeg supports would make it very complex and difficult to use, so it would be better to use FFmpeg directly.

As for profile and preset, I recommend making them mandatory to specify. If not specified, there will still be a default value, which might result in low video quality, and users might not notice this parameter. By making it mandatory, it will be easier for users to know how to adjust it.

**Comment by jb-alvarado** [comment]
> The transcoding feature is a subset of FFmpeg, limited to protocols supported by RTMP, so there's no need to support VP8/VP9/AV1 at the moment.

There is [work](https://github.com/veovera/enhanced-rtmp) on supporting this other codec too, But yeah maybe is not widely supported.

Is fine, then I just also add x265.

**Review by winlinvip — APPROVED** [review]

**Comment by winlinvip** [comment]
Yep, I know enhanced RTMP has AV1 and Opus support, but SRS doesn't support them right now. We will add other codecs in future.

Thank you for your work. :)

**Comment by pannal** [comment]
Any plans on when you'll add other codecs to RTMP/MPEG-FLV/TS? It'd be awesome if SRS could support those. Especially with many newer GPUs and iGPUs supporting encoding to AV1 natively.

Thanks!

**Pull request merged**
